### ISSUE TITLE
Props required by KindeProvider are optional in Kinde client and hook is missing methods

### ISSUE THREAD

**Issue by South-Paw** [kinde-oss/kinde-auth-react#14]
👋

I noticed while implementing this package that in the [docs](https://kinde.com/docs/developer-tools/react-sdk/#react-sdk) (unless I'm misunderstanding something) the only required props are `domain` and `logoutUri` where as in the TypeScript types for this package, _all_ the props are required

```ts
// @kinde-oss/kinde-auth-react
type KindeProviderProps = {
    audience: string;
    scope: string;
    clientId: string;
    domain: string;
    logoutUri: string;
    redirectUri: string;
    children: react.ReactNode;
    isDangerouslyUseLocalStorage?: boolean;
    onRedirectCallback?: () => void;
};
```

then upon looking at the types for the [kinde-oss/kinde-auth-pkce-js](https://github.com/kinde-oss/kinde-auth-pkce-js) client, this is it's [interface](https://github.com/kinde-oss/kinde-auth-pkce-js/blob/main/index.d.ts#L18-L29)

```ts
// @kinde-oss/kinde-auth-pkce-js
export type KindeClientOptions = {
  audience?: string;
  client_id?: string;
  redirect_uri: string;
  domain: string;
  is_dangerously_use_local_storage?: boolean;
  logout_uri?: string;
  on_redirect_callback?: (user: KindeUser, appState?: any) => void;
  scope?: string;
  _framework?: string;
  _frameworkVersion?: string;
};
```

I think that `@kinde-oss/kinde-auth-react`'s types should be corrected to match your clients interface and so the docs align with the types?

```ts
// suggested changes to @kinde-oss/kinde-auth-react
type KindeProviderProps = {
    audience?: string;
    scope?: string;
    clientId?: string;
    domain: string;
    logoutUri?: string;
    redirectUri: string;
    children: react.ReactNode;
    isDangerouslyUseLocalStorage?: boolean;
    onRedirectCallback?: () => void;
};
```

**Comment by South-Paw** [comment]
Also just noticed that the [SDK Reference](https://kinde.com/docs/developer-tools/react-sdk/#sdk-api-reference) in the docs also doesn't align with the current types

**Comment by South-Paw** [comment]
Additionally, there are missing return properties from the `useKindeAuth` hook's return type of `KindeContextProps`, these are

- `getToken`
- `getUser` (though you can access via the `user` key)

without the `getToken` method though there is no way to get the users access token that you want send with an API request

**Comment by DaveOrDead** [comment]
Hey @South-Paw thanks for the catches. I've updated the interfaces and we'll get onto the API reference docs
