### ISSUE TITLE
Question: How I can verify jwt token at the backend side?

### ISSUE THREAD

**Issue by hdlinh1808** [kinde-oss/kinde-auth-react#44]
### Prerequisites

- [X] I have searched the repository’s issues and the [Kinde community](https://thekindecommunity.slack.com/archives/C057M2BQ6LV) to ensure my documentation issue isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### How can we improve the docs or what is missing?

About secret salt

### Provide extra context, such as what you were trying to do and your requirements

Hi I found in documentation that:
![image](https://github.com/kinde-oss/kinde-auth-react/assets/56437153/0c817faf-c2f7-498d-84ed-318f5a85a591)
But I have no way to get the secret salt, how can I verify jwt token from my backend API?
Thank you very much

Linh

**Comment by DaveOrDead** [comment]
Hey @hdlinh1808 I'm not entirely sure what you mean by secret salt, but we do have a [doc on verifying JWTs](https://kinde.com/docs/developer-tools/verifying-json-web-tokens/#json-web-key) 

 if you're looking for your JWKS file you can find this at `https://<your_subdomain>.kinde.com/.well-known/jwks`

In terms of how you verify the JWT this will depend on what technology are you using on your backend.

Here is a rough example in NodeJS but you can do it in whatever technology your API is
```
import jwksClient from "jwks-rsa";
import jwt from "jsonwebtoken";

const client = jwksClient({
  jwksUri: `https://<your_subdomain>.kinde.com/.well-known/jwks`,
});

export async function checkJWT(req) {
  try {
    const authHeader = req.headers.authorization;
    const token = authHeader && authHeader.split(' ')[1];

    //verify token
    const { header } = jwt.decode(token, { complete: true });
    const { kid } = header;
    const key = await client.getSigningKey(kid);
    const signingKey = key.getPublicKey();

    const payload = await jwt.verify(token, signingKey);
    const { data } = payload;

    // Do something with payload here
    console.log({ data });
  } catch (err) {
    if (err instanceof Error) {
      console.error(err.message);
    }
  }
}
```
