### ISSUE TITLE
Bug: React-SDK Doesn't incorporate force token refresh

### ISSUE THREAD

**Issue by samirpdl** [kinde-oss/kinde-auth-react#57]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

The React-SDK does not have forced token refresh, which is available in the JS SDK (https://github.com/kinde-oss/kinde-auth-pkce-js/blob/main/src/createKindeClient.ts#L213). This is causing issues related to another piece of code available in the JS SDK(https://github.com/kinde-oss/kinde-auth-pkce-js/blob/main/src/utils/isJWTActive/isJWTActive.ts#L6). The addition of LEEWAY doesn't immediately refresh the token; it waits for 60 seconds before refreshing. This causes issues when the token has just expired and there is an API request in progress that doesn't refresh. This can be resolved in two ways: Remove LEEWAY from the JS SDK or add a forceRefresh option to the react-sdk.

### Library URL

https://github.com/kinde-oss/kinde-auth-react

### Library version

4.0.2

### Operating system(s)

macOS

### Operating system version(s)

ALL

**Comment by toanbuise** [comment]
I am also facing a similar issue and hope someone can help resolve it. Thanks

**Comment by samirpdl** [comment]
Sent a PR : https://github.com/kinde-oss/kinde-auth-pkce-js/pull/77

**Comment by DanielRivers** [comment]
PR all merged and released version 4.0.4
